module sspopchk_unit
    import ariane_pkg::*;
#(
    parameter config_pkg::cva6_cfg_t CVA6Cfg = config_pkg::cva6_cfg_empty,
    parameter type fu_data_t = logic,
    parameter type exception_t = logic
) (
    // Subsystem clock - SUBSYSTEM
    input logic clk_i,
    // Asynchronous reset active low - SUBSYSTEM
    input logic rst_ni,
    // FU data - ISSUE_STAGE
    input fu_data_t [CVA6Cfg.NrIssuePorts-1:0] fu_data_i,
    // LSU instruction is valid - ISSUE_STAGE
    input logic [CVA6Cfg.NrIssuePorts-1:0] lsu_valid_i,
    // Load instruction ID - LSU
    input logic [CVA6Cfg.TRANS_ID_BITS-1:0] load_trans_id_i,
    // Load result is valid - LSU
    input logic load_valid_i,
    // Load result valid - ISSUE_STAGE
    input logic [CVA6Cfg.XLEN-1:0] load_result_i,
    // Exception generated by load instruction - ISSUE_STAGE
    input exception_t ld_ex_i,
    // Shadow Stack Enabled state
    input logic xsse_i,
    // Exception generated by load instruction - ISSUE_STAGE
    output exception_t load_exception_o
);

    logic current_instruction_is_sspopchk_d, current_instruction_is_sspopchk_q;
    logic ssv_loaded;
    logic [CVA6Cfg.TRANS_ID_BITS-1:0] sspopchk_trans_id_d, sspopchk_trans_id_q;
    logic [CVA6Cfg.XLEN-1:0] link_reg_d, link_reg_q;
    exception_t sspopchk_ex;

    assign ssv_loaded = (sspopchk_trans_id_q == load_trans_id_i) && load_valid_i && current_instruction_is_sspopchk_q;

    always_comb begin
        current_instruction_is_sspopchk_d = current_instruction_is_sspopchk_q;
        sspopchk_trans_id_d = sspopchk_trans_id_q;
        link_reg_d = link_reg_q;
        for (int unsigned i = 0; i < CVA6Cfg.NrIssuePorts; i++) begin
            if (fu_data_i[i].operation == SSPOPCHK && lsu_valid_i[i]) begin
                current_instruction_is_sspopchk_d = 1'b1;
                sspopchk_trans_id_d = fu_data_i[i].trans_id;
                link_reg_d = fu_data_i[i].operand_b;
            end else if (ssv_loaded) begin
                current_instruction_is_sspopchk_d = 1'b0;
                sspopchk_trans_id_d = '0;
            end
        end
    end

    always_comb begin : sspopchk
        sspopchk_ex = '0;
        if (ssv_loaded && xsse_i && link_reg_q != load_result_i) begin
            sspopchk_ex.valid = 1'b1;
            sspopchk_ex.cause = riscv::SOFTWARE_CHECK;
            sspopchk_ex.tval = 3;
        end
    end
    
    // Mux between load exception and shadow stack pop check ex
    always_comb begin : mux_ld_sspopchk_ex
        load_exception_o = ld_ex_i;
        if (ssv_loaded && xsse_i && !ld_ex_i.valid)
            load_exception_o = sspopchk_ex;
        else 
            load_exception_o = ld_ex_i;
    end

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (~rst_ni) begin
            current_instruction_is_sspopchk_q <= 1'b0;
            sspopchk_trans_id_q <= '0;
            link_reg_q <= '0;
        end else begin
            current_instruction_is_sspopchk_q <= current_instruction_is_sspopchk_d;
            sspopchk_trans_id_q <= sspopchk_trans_id_d;
            link_reg_q <= link_reg_d;
        end
    end

endmodule